version: "3.9"
services:
  postgres:
    image: postgres:15
    env_file: .env
    restart: unless-stopped
    volumes:
      - "postgres-data:/var/lib/postgresql/data/"

  django:
    build: .
    image: django-docker
    env_file: .env
    environment:
      - "DJANGO_ALLOWED_HOSTS=${MY_DOMAIN}"
      - "DJANGO_CSRF_TRUSTED_ORIGINS=https://${MY_DOMAIN}"
      - "DJANGO_SESSION_COOKIE_SECURE=true"
      - "DJANGO_CSRF_COOKIE_SECURE=true"
      - "DJANGO_SECURE_SSL_REDIRECT=true"
    restart: unless-stopped
    volumes:
      - "staticfiles-data:/var/www/static"
      - "media-data:/var/www/media"
    depends_on:
      - postgres

volumes:
  media-data:
  postgres-data:
  staticfiles-data:
